name: Engine
version: 1.0
main: xyz.favelamc.engine.bukkit.BukkitLoader
author: Reinaldy Oliveira
commands:
  account:
    aliases: conta
    description: Tenha todas as informações de seu perfil
  rank:
    aliases: group
    description: Altere informações de ranks de jogadores